### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [picone/MusicUnionSearch#1]
Hi @picone . I am a graphic designer and opensource enthusiast, I wanted to contribute to your project and i've designed a logo for your project. If you like it, you can use it. If you need something else please let me know. Best Regard.
![music union](https://user-images.githubusercontent.com/36124339/56183260-fb7d2680-603f-11e9-9ab6-18360e1c2191.png)

**Comment by picone** [comment]
Hi,
Thank you for your design! I think blue one is better. You can give me the icon file or create new pull request.

**Comment by mirzazulfan** [comment]
Thanks for your response, i'm glad you liked it. I'll create a pr as soon as possible. :)

**Comment by mirzazulfan** [comment]
Hi again @picone I've created a pull request #2 . . If you need help in the future, don't hesitate to cantact me. Regard!

**Comment by picone** [comment]
Thinks your contribute!
